### ISSUE TITLE
many symbols are not found

### ISSUE THREAD

**Issue by akash213213** [brian-the-dev/tradingview-list#43] opened 2022-09-11 11:23 UTC
Hi, 
from screener 'INDIA'  and exchange 'NSE' many important symbols are missing . Please add below symbols
'BANKNIFTY'
'NIFTY'
'RELIANCE'

request you to add and confirm

**Comment by brian-the-dev** [comment] 2022-09-11 11:28
Duplicate of https://github.com/brian-the-dev/tradingview-list/issues/14, https://github.com/brian-the-dev/tradingview-list/issues/29, https://github.com/brian-the-dev/tradingview-list/issues/30, https://github.com/brian-the-dev/tradingview-list/issues/38, https://github.com/brian-the-dev/tradingview-list/issues/39.

**Closed by brian-the-dev** 2022-09-11 11:28 UTC

**Comment by akash213213** [comment] 2022-09-11 11:29
Hi brian , can it be done?

**Comment by brian-the-dev** [comment] 2022-09-11 11:33
Please read the readme:

> Please note that indices are not supported by tradingview-ta, this is a limitation from TradingView's API, not the library.
