### ISSUE TITLE
What is the symbol for banknifty and nifty50 index

### ISSUE THREAD

**Issue by anandmanika** [brian-the-dev/tradingview-list#42] opened 2022-09-08 16:04 UTC
TA_Handler(
                symbol= 'BANKBEES', 
                screener = 'INDIA',
                exchange= 'NSE',
                interval=Interval.INTERVAL_15_MINUTES
            )

What should be the symbol for nifty50 and banknifty indices

**Comment by brian-the-dev** [comment] 2022-09-11 11:28
Duplicate of #14, #29, #30, #38, #39.

**Closed by brian-the-dev** 2022-09-11 11:28 UTC
