### ISSUE TITLE
Add NSE Nifty symbol into list.

### ISSUE THREAD

**Issue by bhosalevishal** [brian-the-dev/tradingview-list#30] opened 2022-06-08 00:29 UTC
Add NSE Nifty symbol into list.

Screener: india
Exchange: NSE
Symbol: BankNifty
Description: NSE BankNifty Index

**Comment by brian-the-dev** [comment] 2022-06-08 11:11
Indices (index) are not supported by TradingView nor the tradingview-ta library (see README.md). Also a duplicate of #14. Closing this issue.

**Closed by brian-the-dev** 2022-06-08 11:11 UTC
